/** Evidence taxonomy — 21 categories mapped to Obsedian modules. */

export const EVIDENCE_COVERAGE = [
  {
    id: 'identity',
    title: 'Identity',
    examples: 'User accounts, profiles, device owners, contacts, domain accounts',
    tools: ['Obsedian Prism', 'Obsedian Iris', 'Documents', 'Obsedian Volume'],
    toolIds: ['prism', 'iris', 'documents', 'volume'],
  },
  {
    id: 'communication',
    title: 'Communication',
    examples: 'SMS, WhatsApp, Signal, email, VoIP, call logs, contact relationships',
    tools: ['Obsedian Volume', 'IPDR forensics', 'Obsedian Molecules'],
    toolIds: ['volume', 'ipdr', 'molecules'],
  },
  {
    id: 'browser',
    title: 'Browser',
    examples: 'History, downloads, cookies, bookmarks, passwords, autofill, sessions',
    tools: ['Obsedian Volume', 'Raw Organizer'],
    toolIds: ['volume', 'raw-organizer'],
  },
  {
    id: 'filesystem',
    title: 'File system',
    examples: 'Paths, hashes, timestamps, ownership, deleted files, alternate streams',
    tools: ['Obsedian Volume', 'Chain of Custody'],
    toolIds: ['volume', 'coc'],
  },
  {
    id: 'documents',
    title: 'Documents',
    examples: 'Word, PDF, Excel, PowerPoint — author, metadata, hidden text',
    tools: ['Documents', 'Obsedian Lens'],
    toolIds: ['documents', 'lens'],
  },
  {
    id: 'image',
    title: 'Image',
    examples: 'EXIF, GPS, PRNU, sensor fingerprint, OCR, face embeddings, deepfake signals',
    tools: ['Photo analysis', 'Obsedian Prism', 'Batch ingestion'],
    toolIds: ['face-analyze', 'prism', 'batch-detection'],
  },
  {
    id: 'video',
    title: 'Video',
    examples: 'Codecs, scene changes, face tracking, object detection, OCR, audio extraction',
    tools: ['Video processing', 'Live identification'],
    toolIds: ['video', 'live-id'],
  },
  {
    id: 'audio',
    title: 'Audio',
    examples: 'Speaker embeddings, MFCC, diarization, compression artifacts',
    tools: ['Voice analysis'],
    toolIds: ['voice'],
  },
  {
    id: 'location',
    title: 'Location',
    examples: 'GPS, cell towers, Wi-Fi, Bluetooth, travel history, geofencing',
    tools: ['Obsedian Volume', 'Obsedian Molecules'],
    toolIds: ['volume', 'molecules'],
  },
  {
    id: 'cloud',
    title: 'Cloud',
    examples: 'Login history, sync, uploads, share links, AWS, M365, Google Workspace',
    tools: ['Obsedian Volume', 'EDR forensics'],
    toolIds: ['volume', 'edr'],
  },
  {
    id: 'social',
    title: 'Social media',
    examples: 'Posts, friends, followers, stories, group memberships, shared media',
    tools: ['Obsedian Volume', 'Obsedian Molecules'],
    toolIds: ['volume', 'molecules'],
  },
  {
    id: 'application',
    title: 'Application',
    examples: 'Install times, usage frequency, internal databases, cache, tokens, sessions',
    tools: ['Obsedian Volume'],
    toolIds: ['volume'],
  },
  {
    id: 'registry',
    title: 'Registry (Windows)',
    examples: 'USB history, program execution, network settings, mounted drives, RDP',
    tools: ['Obsedian Volume'],
    toolIds: ['volume'],
  },
  {
    id: 'execution',
    title: 'Execution',
    examples: 'Process creation, PowerShell history, bash history, scheduled tasks, services',
    tools: ['EDR forensics', 'RAM Dumper'],
    toolIds: ['edr', 'ram-dump'],
  },
  {
    id: 'network',
    title: 'Network',
    examples: 'IP addresses, DNS, MAC, VPN, browser connections, sessions, open ports',
    tools: ['IPDR forensics', 'EDR forensics'],
    toolIds: ['ipdr', 'edr'],
  },
  {
    id: 'memory',
    title: 'Memory (RAM)',
    examples: 'Processes, injected code, DLLs, decrypted strings, encryption keys, malware',
    tools: ['RAM Dumper', 'Rootkit and fileless'],
    toolIds: ['ram-dump', 'rootkit'],
  },
  {
    id: 'mobile',
    title: 'Mobile-specific',
    examples: 'Apps, notifications, screen time, biometrics metadata, SIM history, pairings',
    tools: ['Obsedian Volume'],
    toolIds: ['volume'],
  },
  {
    id: 'vehicle',
    title: 'Vehicle',
    examples: 'GPS routes, Bluetooth pairings, call history, navigation destinations',
    tools: ['Obsedian Volume'],
    toolIds: ['volume'],
  },
  {
    id: 'crypto',
    title: 'Cryptocurrency',
    examples: 'Wallet IDs, transaction IDs, exchange accounts, seed phrase artifacts',
    tools: ['Obsedian Volume'],
    toolIds: ['volume'],
  },
  {
    id: 'ai-cv',
    title: 'AI / computer vision',
    examples: 'Face embeddings, landmarks, object classification, OCR, similarity search',
    tools: ['Obsedian Prism', 'Photo analysis', 'Video processing', 'Live identification'],
    toolIds: ['prism', 'face-analyze', 'video', 'live-id'],
  },
  {
    id: 'correlation',
    title: 'Correlation',
    examples: 'Entity graphs, relationship graphs, communication graphs, timeline graphs',
    tools: ['Obsedian Molecules'],
    toolIds: ['molecules'],
  },
]

export const COVERAGE_INTRO = {
  title: '21 evidence categories. One forensic OS.',
  subtitle:
    'Obsedian Forensics covers the full digital evidence taxonomy — from identity and communication to memory, network, and correlation graphs. Every category maps to specific modules in the platform.',
}
