/** Obsedian product ecosystem — product families for marketing pages. */

/** Active intelligence learning loop — powered by Obsedian INsight */
export const INSIGHT_LEARNING_LOOP = [
  { id: 'evidence', label: 'Evidence' },
  { id: 'analysis', label: 'Analysis' },
  { id: 'molecules', label: 'Molecules', productSlug: 'molecules' },
  { id: 'lens', label: 'Lens', productSlug: 'lens' },
  { id: 'feedback', label: 'Human feedback' },
  { id: 'insight', label: 'INsight', productSlug: 'insight' },
  { id: 'knowledge', label: 'Knowledge updates' },
  { id: 'models', label: 'Model updates' },
  { id: 'future', label: 'Future investigations' },
]

export const PRODUCT_FAMILIES = {
  foundation: {
    id: 'foundation',
    label: 'Foundation',
    tagline: 'Acquire and preserve evidence with integrity from the first byte.',
    accent: '#34d399',
  },
  analysis: {
    id: 'analysis',
    label: 'Analysis Engines',
    tagline: 'Biometric, media, and document intelligence powered by branded engines.',
    accent: '#a78bfa',
  },
  dfir: {
    id: 'dfir',
    label: 'DFIR & Cyber',
    tagline: 'Endpoint, network, and threat intelligence for cyber investigations.',
    accent: '#fb923c',
  },
  intelligence: {
    id: 'intelligence',
    label: 'Intelligence Layer',
    tagline: 'Subject profiles, correlation graphs, AI investigation — and a learning loop that improves every case.',
    accent: '#7c4dff',
  },
  operations: {
    id: 'operations',
    label: 'Operations',
    tagline: 'Workflow, collaboration, reporting, and case management at scale.',
    accent: '#94a3b8',
  },
}

export const FAMILY_ORDER = ['foundation', 'analysis', 'dfir', 'intelligence', 'operations']

export const JOURNEY_STEPS = {
  acquire: { id: 'acquire', label: 'Acquire', order: 1 },
  preserve: { id: 'preserve', label: 'Preserve', order: 2 },
  analyze: { id: 'analyze', label: 'Analyze', order: 3 },
  correlate: { id: 'correlate', label: 'Correlate', order: 4 },
  investigate: { id: 'investigate', label: 'Investigate', order: 5 },
  report: { id: 'report', label: 'Report', order: 6 },
}

/** Maps legacy /features/:id routes to new product slugs */
export const LEGACY_FEATURE_REDIRECTS = {
  coc: 'chain',
  volume: 'volume',
  'ram-dump': 'pulse',
  'raw-organizer': 'scout',
  'batch-detection': 'scout',
  prism: 'prism',
  iris: 'iris',
  voice: 'echo',
  'face-analyze': 'spectra',
  spectra: 'spectra',
  video: 'motion',
  'live-id': 'live',
  fingerprint: 'ridge',
  documents: 'folio',
  'id-card': 'folio',
  edr: 'sentinel',
  ipdr: 'nexus',
  rootkit: 'phantom',
  molecules: 'molecules',
  lens: 'lens',
}

export const PRODUCTS = [
  {
    id: 'chain',
    slug: 'chain',
    shortName: 'Chain',
    family: 'foundation',
    label: 'Obsedian Chain',
    role: 'Chain of Custody & Evidence Integrity',
    description:
      'Forensic copy, cryptographic hashing, and audit trails — prove evidence integrity before analysis begins.',
    overview:
      'Obsedian Chain is the integrity foundation of every investigation. Create forensic copies, compute hashes, maintain court-ready audit trails, and document every handoff — so your team can demonstrate evidence was never altered.',
    highlights: ['Evidence acquisition', 'Integrity verification', 'Audit trails', 'Court-ready documentation'],
    journey: ['acquire', 'preserve'],
    relatedProducts: ['vault', 'volume'],
    heroProduct: false,
    animation: 'coc',
    icon: 'coc',
    legacyId: 'coc',
    idealFor: ['Seizure documentation', 'Court admissibility', 'Multi-analyst handoffs'],
    proof: 'SHA-256 hash verification at ingest',
  },
  {
    id: 'vault',
    slug: 'vault',
    shortName: 'Vault',
    family: 'foundation',
    label: 'Obsedian Vault',
    role: 'Evidence Repository',
    description:
      'Secure evidence storage with access control, lifecycle management, and legal hold support.',
    overview:
      'Obsedian Vault is the secure evidence repository for your organization. Store seized media, case artifacts, and investigation outputs with role-based access, retention policies, and legal hold — all on infrastructure you control.',
    highlights: ['Secure storage', 'Access control', 'Evidence lifecycle management', 'Legal hold support'],
    journey: ['preserve'],
    relatedProducts: ['chain', 'volume', 'command'],
    heroProduct: false,
    animation: 'vault',
    icon: 'disk',
    idealFor: ['Long-term case archives', 'Legal hold compliance', 'Multi-team access control'],
    proof: 'Zero cloud uploads — evidence stays on your servers',
  },
  {
    id: 'volume',
    slug: 'volume',
    shortName: 'Volume',
    family: 'foundation',
    label: 'Obsedian Volume',
    role: 'Evidence Acquisition',
    description:
      'Disk, mobile, cloud, IoT, and vehicle data collection — the acquisition hub for every evidence source.',
    overview:
      'Obsedian Volume ingests hard drives, mobile extractions, cloud artifacts, IoT devices, and vehicle systems. Mount forensic images, catalog files, calls, apps, and filesystem metadata — then hand off to every analysis product in the ecosystem.',
    highlights: ['Disk acquisition', 'Mobile acquisition', 'Cloud acquisition', 'IoT and vehicle data collection'],
    journey: ['acquire', 'analyze'],
    relatedProducts: ['chain', 'scout', 'pulse'],
    heroProduct: true,
    animation: 'disk',
    icon: 'disk',
    legacyId: 'volume',
    idealFor: ['Laptop and phone seizure', 'Mobile call analysis', 'Raid evidence triage'],
    proof: 'One hub for computer, mobile, and vehicle evidence',
  },
  {
    id: 'pulse',
    slug: 'pulse',
    shortName: 'Pulse',
    family: 'foundation',
    label: 'Obsedian Pulse',
    role: 'Memory & Live Response',
    description:
      'Volatile memory capture, live response, and incident investigations before evidence disappears.',
    overview:
      'Obsedian Pulse captures volatile memory from live systems — running processes, injected code, network sessions, encryption keys, and malware indicators. Essential for incident response and fileless malware investigation.',
    highlights: ['Memory capture', 'Live response', 'Volatile evidence preservation', 'Incident investigations'],
    journey: ['acquire', 'preserve', 'analyze'],
    relatedProducts: ['volume', 'sentinel', 'phantom'],
    heroProduct: false,
    animation: 'ram',
    icon: 'ram',
    legacyId: 'ram-dump',
    idealFor: ['Live incident response', 'Rootkit hunts', 'Encryption key recovery'],
    proof: 'Recover evidence that never touches disk',
  },
  {
    id: 'scout',
    slug: 'scout',
    shortName: 'Scout',
    family: 'foundation',
    label: 'Obsedian Scout',
    role: 'Rapid Triage',
    description:
      'Fast evidence review, threat indicators, and investigation prioritization for time-critical cases.',
    overview:
      'Obsedian Scout accelerates initial case assessment. Structure raw dumps, triage mixed evidence batches, surface threat indicators, and prioritize what deserves deep analysis — so investigators act on intelligence, not backlog.',
    highlights: ['Fast evidence review', 'Threat indicators', 'Investigation prioritization', 'Quick intelligence generation'],
    journey: ['analyze', 'investigate'],
    relatedProducts: ['volume', 'phantom', 'molecules'],
    heroProduct: false,
    animation: 'raw',
    icon: 'batch',
    legacyId: 'raw-organizer',
    idealFor: ['Raid triage', 'Mixed evidence drops', 'Cold-case imports'],
    proof: 'Multi-type bulk processing in one job',
  },
  {
    id: 'prism',
    slug: 'prism',
    shortName: 'Prism',
    family: 'analysis',
    label: 'Obsedian Prism',
    role: 'Facial Intelligence',
    description:
      'Face recognition, verification, subject profiling, and facial analytics on every subject record.',
    overview:
      'Obsedian Prism is the face intelligence engine. Enroll subjects, verify 1:1, search 1:N, index facial landmarks and distinguishing features — with full audit trails on infrastructure you control.',
    highlights: ['Face recognition', 'Face verification', 'Subject profiling', 'Facial analytics'],
    journey: ['analyze'],
    relatedProducts: ['persona', 'iris', 'live'],
    heroProduct: true,
    animation: 'prism',
    icon: 'prism',
    legacyId: 'prism',
    idealFor: ['Suspect identification', 'Watchlist screening', 'Court-ready identity confirmation'],
    proof: 'Sub-second 1:N search on local infrastructure',
  },
  {
    id: 'iris',
    slug: 'iris',
    shortName: 'Iris',
    family: 'analysis',
    label: 'Obsedian Iris',
    role: 'Iris Intelligence',
    description:
      'Iris matching, identity verification, and biometric search linked to unified subject records.',
    overview:
      'Obsedian Iris captures the unique pattern of each eye for enrollment, 1:1 verification, and 1:N search — linked to the same subject records as Prism for multi-modal identity confirmation.',
    highlights: ['Iris matching', 'Identity verification', 'Biometric search'],
    journey: ['analyze'],
    relatedProducts: ['prism', 'ridge', 'folio'],
    heroProduct: false,
    animation: 'iris',
    icon: 'iris',
    legacyId: 'iris',
    idealFor: ['Border screening', 'High-security access', 'Multi-modal identity'],
    proof: 'Dedicated iris engine — not an afterthought modality',
  },
  {
    id: 'echo',
    slug: 'echo',
    shortName: 'Echo',
    family: 'analysis',
    label: 'Obsedian Echo',
    role: 'Voice Intelligence',
    description:
      'Speaker recognition, voice comparison, audio enhancement, and call intelligence.',
    overview:
      'Obsedian Echo diarizes multiple speakers, clusters unknown voices, matches to enrolled subjects, and surfaces communication patterns — feeding Obsedian Molecules for relationship mapping.',
    highlights: ['Speaker recognition', 'Voice comparison', 'Audio enhancement', 'Call intelligence'],
    journey: ['analyze', 'correlate'],
    relatedProducts: ['persona', 'folio', 'lens'],
    heroProduct: false,
    animation: 'audio',
    icon: 'audio',
    legacyId: 'voice',
    idealFor: ['Wiretap analysis', 'Multi-speaker interviews', 'Communication mapping'],
    proof: 'Multi-speaker diarization in one recording',
  },
  {
    id: 'spectra',
    slug: 'spectra',
    shortName: 'Spectra',
    family: 'analysis',
    label: 'Obsedian Spectra',
    role: 'Image Intelligence',
    description:
      'OCR, metadata extraction, object detection, and deepfake detection from any evidence image.',
    overview:
      'Obsedian Spectra extracts the full artifact stack from evidence images — EXIF, GPS, PRNU sensor fingerprints, editing traces, OCR, object detection, and deepfake indicators — feeding Prism, Molecules, and Lens.',
    highlights: ['OCR', 'Metadata extraction', 'Object detection', 'Deepfake detection'],
    journey: ['analyze'],
    relatedProducts: ['prism', 'persona', 'motion'],
    heroProduct: true,
    animation: 'spectra',
    icon: 'spectra',
    legacyId: 'face-analyze',
    idealFor: ['Camera attribution', 'Image authenticity', 'Unknown subject profiling'],
    proof: 'PRNU and sensor fingerprinting built in',
  },
  {
    id: 'motion',
    slug: 'motion',
    shortName: 'Motion',
    family: 'analysis',
    label: 'Obsedian Motion',
    role: 'Video Intelligence',
    description:
      'Object tracking, face tracking, CCTV analytics, and timeline generation from video evidence.',
    overview:
      'Obsedian Motion ingests surveillance, bodycam, and interview footage — detecting faces and objects in every frame, matching against your database, and building searchable timelines for case reports.',
    highlights: ['Object tracking', 'Face tracking', 'CCTV analytics', 'Timeline generation'],
    journey: ['analyze'],
    relatedProducts: ['live', 'prism', 'chronos'],
    heroProduct: false,
    animation: 'video',
    icon: 'video',
    legacyId: 'video',
    idealFor: ['CCTV review', 'Bodycam analysis', 'Event reconstruction'],
    proof: 'Database matching for people and entities',
  },
  {
    id: 'live',
    slug: 'live',
    shortName: 'Live',
    family: 'analysis',
    label: 'Obsedian Live',
    role: 'Real-Time Intelligence',
    description:
      'Live monitoring, watchlists, real-time alerts, and multi-camera intelligence.',
    overview:
      'Obsedian Live connects to any CCTV, IP camera, or remote stream — detecting faces, objects, and entities in every frame and matching against enrolled databases in real time with instant alerts.',
    highlights: ['Live monitoring', 'Watchlists', 'Real-time alerts', 'Multi-camera intelligence'],
    journey: ['analyze', 'investigate'],
    relatedProducts: ['prism', 'motion', 'command'],
    heroProduct: false,
    animation: 'live',
    icon: 'live',
    legacyId: 'live-id',
    idealFor: ['Checkpoint screening', 'Event security', 'Multi-entity surveillance'],
    proof: 'Any camera — matching happens locally',
  },
  {
    id: 'ridge',
    slug: 'ridge',
    shortName: 'Ridge',
    family: 'analysis',
    label: 'Obsedian Ridge',
    role: 'Fingerprint Intelligence',
    description:
      'Fingerprint matching, latent print enhancement, and AFIS integration alongside face records.',
    overview:
      'Obsedian Ridge enrolls ridge patterns from scans or photos, enhances latent prints, and matches unknown prints against your database — linked to the same subject records as Prism and Iris.',
    highlights: ['Fingerprint matching', 'Latent print enhancement', 'AFIS integration'],
    journey: ['analyze'],
    relatedProducts: ['prism', 'iris', 'folio'],
    heroProduct: false,
    animation: 'fingerprint',
    icon: 'fingerprint',
    legacyId: 'fingerprint',
    idealFor: ['Crime scene latents', 'Border enrollment', 'Multi-modal confirmation'],
    proof: 'Second biometric layer on unified subject records',
  },
  {
    id: 'folio',
    slug: 'folio',
    shortName: 'Folio',
    family: 'analysis',
    label: 'Obsedian Folio',
    role: 'Document Intelligence',
    description:
      'Document analysis, OCR, metadata extraction, and identity document verification.',
    overview:
      'Obsedian Folio ingests Word, PDF, Excel, PowerPoint, and identity documents — extracting text, metadata, and embedded artifacts with semantic search and page citations. ID photos cross-check against Prism automatically.',
    highlights: ['Document analysis', 'OCR', 'Metadata extraction', 'Identity document verification'],
    journey: ['analyze', 'investigate'],
    relatedProducts: ['lens', 'prism', 'brief'],
    heroProduct: false,
    animation: 'document',
    icon: 'document',
    legacyId: 'documents',
    idealFor: ['Chargesheet review', 'Cross-case document search', 'ID fraud detection'],
    proof: 'Semantic search with exact page citations',
  },
  {
    id: 'sentinel',
    slug: 'sentinel',
    shortName: 'Sentinel',
    family: 'dfir',
    label: 'Obsedian Sentinel',
    role: 'Endpoint Intelligence',
    description:
      'Endpoint visibility, threat detection, behavioral analytics, and incident response.',
    overview:
      'Obsedian Sentinel ingests endpoint detection and response data — process creation, execution traces, PowerShell logs, and persistence mechanisms — correlating endpoint activity with Volume, Pulse, and Molecules.',
    highlights: ['Endpoint visibility', 'Threat detection', 'Behavioral analytics', 'Incident response'],
    journey: ['analyze', 'investigate'],
    relatedProducts: ['pulse', 'phantom', 'nexus'],
    heroProduct: false,
    animation: 'edr',
    icon: 'edr',
    legacyId: 'edr',
    idealFor: ['Incident response', 'APT investigation', 'Insider threat analysis'],
    proof: 'Full endpoint execution timeline',
  },
  {
    id: 'nexus',
    slug: 'nexus',
    shortName: 'Nexus',
    family: 'dfir',
    label: 'Obsedian Nexus',
    role: 'Network Intelligence',
    description:
      'Network forensics, DNS intelligence, traffic analysis, and session reconstruction.',
    overview:
      'Obsedian Nexus analyzes IP detail records, DNS requests, firewall logs, and network sessions — reconstructing communication patterns that feed Obsedian Molecules for full attack and comms mapping.',
    highlights: ['Network forensics', 'DNS intelligence', 'Traffic analysis', 'Session reconstruction'],
    journey: ['analyze', 'correlate'],
    relatedProducts: ['sentinel', 'molecules', 'chronos'],
    heroProduct: false,
    animation: 'ipdr',
    icon: 'ipdr',
    legacyId: 'ipdr',
    idealFor: ['Telecom investigations', 'Network intrusion', 'Communication mapping'],
    proof: 'VPN and proxy-aware session reconstruction',
  },
  {
    id: 'phantom',
    slug: 'phantom',
    shortName: 'Phantom',
    family: 'dfir',
    label: 'Obsedian Phantom',
    role: 'Threat & Malware Intelligence',
    description:
      'Malware analysis, rootkit detection, threat hunting, and persistence analysis.',
    overview:
      'Obsedian Phantom correlates memory artifacts from Pulse with disk and endpoint indicators — surfacing hidden processes, injected code, kernel hooks, and fileless malware that evades traditional scans.',
    highlights: ['Malware analysis', 'Rootkit detection', 'Threat hunting', 'Persistence analysis'],
    journey: ['analyze', 'investigate'],
    relatedProducts: ['pulse', 'sentinel', 'chronos'],
    heroProduct: false,
    animation: 'rootkit',
    icon: 'rootkit',
    legacyId: 'rootkit',
    idealFor: ['Rootkit investigation', 'Fileless malware hunts', 'APT cases'],
    proof: 'Memory + disk + endpoint correlation',
  },
  {
    id: 'persona',
    slug: 'persona',
    shortName: 'Persona',
    family: 'intelligence',
    label: 'Obsedian Persona',
    role: 'Subject Intelligence Engine',
    description:
      'Build a complete profile of an individual — face, voice, phone, email, vehicle, locations, documents, and relationships in one subject record.',
    overview:
      'A suspect is not a face. Obsedian Persona is the subject intelligence layer between modality engines and Molecules — fusing biometrics, communications, devices, locations, and documents into unified profiles that investigators can query, enrich, and correlate.',
    highlights: [
      'Unified subject profiles',
      'Multi-modal identity fusion',
      'Phone, email, and comms linking',
      'Location and vehicle association',
      'Document and relationship indexing',
    ],
    journey: ['analyze', 'correlate'],
    relatedProducts: ['prism', 'echo', 'folio', 'molecules'],
    heroProduct: false,
    comingSoon: true,
    animation: 'persona',
    icon: 'prism',
    idealFor: ['Suspect dossiers', 'Multi-source identity resolution', 'Unknown subject enrichment'],
    proof: 'One subject — every modality and artifact type together',
  },
  {
    id: 'molecules',
    slug: 'molecules',
    shortName: 'Molecules',
    family: 'intelligence',
    label: 'Obsedian Molecules',
    role: 'Knowledge Graph',
    description:
      'Entity relationships, evidence correlation, communication mapping, and investigation intelligence.',
    overview:
      'Obsedian Molecules builds entity, communication, timeline, device, and movement graphs from every evidence source — the investigative differentiator where modern forensic platforms derive most of their value.',
    highlights: ['Entity relationships', 'Evidence correlation', 'Communication mapping', 'Investigation intelligence'],
    journey: ['correlate'],
    relatedProducts: ['persona', 'chronos', 'lens', 'insight'],
    heroProduct: true,
    animation: 'graph',
    icon: 'graph',
    legacyId: 'molecules',
    idealFor: ['Organized crime mapping', 'Network analysis', 'Stakeholder briefings'],
    proof: 'Graphs from every module — not manual spreadsheets',
  },
  {
    id: 'chronos',
    slug: 'chronos',
    shortName: 'Chronos',
    family: 'intelligence',
    label: 'Obsedian Chronos',
    role: 'Timeline Intelligence',
    description:
      'Unified timelines, event reconstruction, activity correlation, and investigation context.',
    overview:
      'Obsedian Chronos reconstructs unified investigation timelines from disk artifacts, network sessions, communications, and biometric hits — giving investigators chronological context that single tools cannot provide.',
    highlights: ['Unified timelines', 'Event reconstruction', 'Activity correlation', 'Investigation context'],
    journey: ['correlate', 'investigate'],
    relatedProducts: ['molecules', 'nexus', 'brief'],
    heroProduct: false,
    animation: 'chronos',
    icon: 'graph',
    idealFor: ['Attack reconstruction', 'Alibi verification', 'Multi-source event ordering'],
    proof: 'Cross-modal timeline from every evidence type',
  },
  {
    id: 'lens',
    slug: 'lens',
    shortName: 'Lens',
    family: 'intelligence',
    label: 'Obsedian Lens',
    role: 'AI Investigation Assistant',
    description:
      'Natural language search, investigation assistance, automated summaries, and report generation support.',
    overview:
      'Obsedian Lens is the natural-language query layer across the entire ecosystem. Ask cross-modal questions spanning biometrics, media, documents, and network records — with cited answers your team can verify.',
    highlights: ['Natural language search', 'Investigation assistance', 'Automated summaries', 'Report generation support'],
    journey: ['investigate', 'report'],
    relatedProducts: ['molecules', 'insight', 'brief', 'folio'],
    heroProduct: true,
    animation: 'lens',
    icon: 'lens',
    legacyId: 'lens',
    idealFor: ['Ad-hoc case questions', 'Leadership briefings', 'Cross-evidence queries'],
    proof: 'Read-only queries — safe for production data',
  },
  {
    id: 'insight',
    slug: 'insight',
    shortName: 'INsight',
    family: 'intelligence',
    label: 'Obsedian INsight',
    role: 'Active Intelligence & Learning Loop',
    description:
      'Turn investigator feedback into continuously improving intelligence — confidence scoring, graph reinforcement, and recommendations for future cases.',
    overview:
      'Obsedian INsight closes the loop after Lens. Human feedback refines entity resolution, reinforces Molecules graphs, mines investigation patterns, and drives knowledge and model updates — so every case makes the next investigation smarter.',
    highlights: [
      'Feedback collection',
      'Confidence scoring',
      'Entity resolution',
      'Graph reinforcement',
      'Investigation pattern mining',
      'Recommendation generation',
      'Active intelligence',
    ],
    journey: ['investigate', 'correlate'],
    relatedProducts: ['lens', 'molecules', 'persona'],
    heroProduct: false,
    comingSoon: true,
    animation: 'insight',
    icon: 'graph',
    idealFor: ['Agency-wide learning systems', 'Analyst feedback loops', 'Proactive case recommendations'],
    proof: 'Every investigation improves the next',
  },
  {
    id: 'flow',
    slug: 'flow',
    shortName: 'Flow',
    family: 'operations',
    label: 'Obsedian Flow',
    role: 'Workflow Automation',
    description:
      'Automated workflows, investigation orchestration, and process automation at scale.',
    overview:
      'Obsedian Flow automates repetitive investigation tasks — evidence routing, triage pipelines, alert escalation, and multi-step workflows — so analysts focus on intelligence, not manual orchestration.',
    highlights: ['Automated workflows', 'Investigation orchestration', 'Process automation'],
    journey: ['investigate'],
    relatedProducts: ['command', 'scout', 'sentinel'],
    heroProduct: false,
    animation: 'flow',
    icon: 'batch',
    idealFor: ['High-volume labs', 'SOC-DFIR handoffs', 'Standard operating procedures'],
    proof: 'Configurable workflows without custom code',
  },
  {
    id: 'review',
    slug: 'review',
    shortName: 'Review',
    family: 'operations',
    label: 'Obsedian Review',
    role: 'Collaborative Review',
    description:
      'Notes, annotations, team collaboration, and evidence review workflows.',
    overview:
      'Obsedian Review enables multi-analyst collaboration on evidence — annotations, review queues, approval workflows, and shared notes — with full audit trails for legal and supervisory review.',
    highlights: ['Notes and annotations', 'Team collaboration', 'Evidence review workflows'],
    journey: ['investigate'],
    relatedProducts: ['command', 'folio', 'brief'],
    heroProduct: false,
    animation: 'document',
    icon: 'document',
    idealFor: ['Multi-analyst cases', 'Supervisory review', 'Peer validation'],
    proof: 'Every annotation logged and attributable',
  },
  {
    id: 'brief',
    slug: 'brief',
    shortName: 'Brief',
    family: 'operations',
    label: 'Obsedian Brief',
    role: 'Reporting Platform',
    description:
      'Investigation reports, evidence summaries, executive reporting, and export capabilities.',
    overview:
      'Obsedian Brief generates court-ready investigation reports, executive summaries, and evidence exports — with cited sources from Folio, Lens, and Molecules for reports stakeholders can trust.',
    highlights: ['Investigation reports', 'Evidence summaries', 'Executive reporting', 'Export capabilities'],
    journey: ['report'],
    relatedProducts: ['lens', 'folio', 'command'],
    heroProduct: false,
    animation: 'document',
    icon: 'document',
    idealFor: ['Court submissions', 'Leadership briefings', 'Compliance reporting'],
    proof: 'Cited evidence in every report section',
  },
  {
    id: 'command',
    slug: 'command',
    shortName: 'Command',
    family: 'operations',
    label: 'Obsedian Command',
    role: 'Case Management',
    description:
      'Case tracking, team management, assignments, and investigation lifecycle management.',
    overview:
      'Obsedian Command is the investigation command center — track cases, assign analysts, manage workloads, and oversee the full investigation lifecycle from seizure to report.',
    highlights: ['Case tracking', 'Team management', 'Assignments', 'Investigation lifecycle management'],
    journey: ['acquire', 'report'],
    relatedProducts: ['vault', 'flow', 'brief'],
    heroProduct: true,
    animation: 'command',
    icon: 'disk',
    idealFor: ['Agency case management', 'Multi-team operations', 'Investigation oversight'],
    proof: 'Enterprise-grade case lifecycle from intake to close',
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) ?? null
}

export function getProductsByFamily(familyId) {
  return PRODUCTS.filter((p) => p.family === familyId)
}

export function getHeroProducts() {
  return PRODUCTS.filter((p) => p.heroProduct)
}

export function getRelatedProducts(slug) {
  const product = getProductBySlug(slug)
  if (!product) return []
  return product.relatedProducts
    .map((id) => getProductBySlug(id))
    .filter(Boolean)
}

export const PLATFORM_PILLARS = [
  {
    id: 'unified',
    title: 'Unified investigations',
    description: 'One ecosystem from seizure to report — not a dozen disconnected vendors.',
  },
  {
    id: 'analytics',
    title: 'Advanced analytics',
    description: 'Biometric, media, network, and document engines built for forensic workloads.',
  },
  {
    id: 'ai',
    title: 'AI-assisted workflows',
    description: 'Lens for investigation copilot; INsight closes the loop — feedback becomes knowledge for future cases.',
  },
  {
    id: 'evidence',
    title: 'Evidence management',
    description: 'Chain, Vault, and Command — integrity, storage, and lifecycle on your infrastructure.',
  },
  {
    id: 'correlation',
    title: 'Intelligence correlation',
    description: 'Persona builds subject profiles; Molecules and Chronos connect people, devices, and timelines.',
  },
  {
    id: 'learning',
    title: 'Active intelligence loop',
    description: 'INsight turns human feedback into graph reinforcement, pattern mining, and smarter future investigations.',
  },
  {
    id: 'scale',
    title: 'Enterprise scalability',
    description: 'Multi-tenant, RBAC, distributed processing, and workflow automation at agency scale.',
  },
]
